# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=2000)),
                ('concept_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
                ('level', models.IntegerField(default=0)),
                ('pct_users', models.FloatField(default=0.0)),
                ('total_users', models.IntegerField(default=0)),
                ('correct_time', models.FloatField(default=0.0)),
                ('correct_users', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserConceptScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_known', models.IntegerField(default=0)),
                ('asked', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('concept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.Concept')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0)),
                ('attempt', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.QuestionBank')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.Test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
