# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
                ('pct_users', models.FloatField(default=0.0)),
                ('total_users', models.IntegerField(default=0)),
                ('correct_time', models.FloatField(default=0.0)),
                ('correct_users', models.IntegerField(default=0)),
            ],
        ),
    ]
