# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconceptscore',
            old_name='concept_id',
            new_name='concept',
        ),
    ]
