# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0002_user_concept_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_concept_score',
            old_name='answered',
            new_name='corrects',
        ),
        migrations.AddField(
            model_name='user_concept_score',
            name='incorrects',
            field=models.IntegerField(default=0),
        ),
    ]
