# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adaptive_learning', '0002_auto_20170904_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_class', models.CharField(max_length=2000)),
                ('user_board', models.CharField(max_length=2000)),
                ('user_subject', models.CharField(max_length=2000)),
                ('user_level', models.IntegerField(default=0)),
                ('user_all', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
