# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0003_auto_20170824_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_bank',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
