# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adaptive_learning', '0004_question_bank_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
                ('level', models.IntegerField(default=0)),
                ('pct_users', models.FloatField(default=0.0)),
                ('total_users', models.IntegerField(default=0)),
                ('correct_time', models.FloatField(default=0.0)),
                ('correct_users', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.QuestionBank')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.Test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='user_concept_score',
            new_name='UserConceptScore',
        ),
        migrations.DeleteModel(
            name='question_bank',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.Test'),
        ),
    ]
