# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0004_remove_userconceptscore_marked_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionscore',
            name='time_taken',
            field=models.FloatField(default=0.0),
        ),
    ]
