# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adaptive_learning', '0006_auto_20170907_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevelScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('attempt', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.QuestionBank')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.Test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
