# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0007_userlevelscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlevelscore',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userlevelscore',
            name='test',
        ),
        migrations.RemoveField(
            model_name='userlevelscore',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserLevelScore',
        ),
    ]
