# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0008_auto_20170908_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionscore',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 8, 14, 37, 47, 230113)),
        ),
        migrations.AlterField(
            model_name='userquestionscore',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 8, 14, 37, 47, 230051)),
        ),
    ]
