# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 09:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adaptive_learning', '0009_auto_20170908_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='result',
            field=models.CharField(default=b'None', max_length=2000),
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userquestionscore',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 9, 9, 13, 25, 998129)),
        ),
        migrations.AlterField(
            model_name='userquestionscore',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 9, 9, 13, 25, 998097)),
        ),
    ]
