# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0010_auto_20170909_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionscore',
            name='time_taken',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userquestionscore',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 9, 16, 10, 38, 965742)),
        ),
        migrations.AlterField(
            model_name='userquestionscore',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 9, 16, 10, 38, 965678)),
        ),
    ]
