# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0011_auto_20170909_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionscore',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userquestionscore',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
