# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adaptive_learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
                ('concept', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.Concept')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.QuestionBank')),
            ],
        ),
        migrations.CreateModel(
            name='UserChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('text_sent', models.CharField(max_length=2000)),
                ('text_recieved', models.CharField(max_length=2000)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
