# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_chat_logs',
            new_name='user_chat_log',
        ),
    ]
