# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0012_auto_20170909_1612'),
        ('chatbot', '0002_auto_20170905_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TopicRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
                ('concept', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.Concept')),
                ('topic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Topic')),
            ],
        ),
    ]
