# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20170731_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='qna_repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('q', models.CharField(max_length=2000)),
                ('a', models.CharField(max_length=2000)),
            ],
        ),
    ]
