# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20170804_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna_repository',
            name='question_id',
            field=models.IntegerField(),
        ),
    ]
