# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20170804_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qna_repository',
            new_name='QnaRepository',
        ),
        migrations.RenameModel(
            old_name='user_chat_log',
            new_name='UserChatLog',
        ),
    ]
